blueprint:
  name: Activate most recent scene
  description: >

    ## Features

    - turns on the most recent scene on the area

    - omit scenes by excluding them

    - add additional scenes by including them

    - define a transition time

    **Version**: 0.1

    Inspiration taken from https://community.home-assistant.io/t/simple-scene-toggle/389779

  source_url: https://github.com/jollierfinbean/ha-blueprint-activate-most-recent-scene/blob/main/activate_most_recent_scene.yaml
  domain: script

  input:
    area:
      name: Name of area
      description: Name of the area where you want to toggle scenes
      default: ""
      selector:
        area:

    included_scenes:
      name: Included Scenes
      description: Additional scenes to be included
      default: []
      selector:
        entity:
          filter:
            domain: scene
          multiple: true

    excluded_scenes:
      name: Excluded Scenes
      description: Scenes to be excluded
      default: []
      selector:
        entity:
          filter:
            domain: scene
          multiple: true

    transition:
      name: Transition time
      description: Transition time when switching between scenes
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: s

mode: queued

variables:
  area: !input "area"
  included_scenes: !input "included_scenes"
  excluded_scenes: !input "excluded_scenes"
  all_scenes: >
    {{
      expand(area_entities(area), included_scenes) |
      selectattr('domain', 'eq', 'scene') |
      reject('in', excluded_scenes) |
      selectattr('state', '!=', 'unknown') |
      sort(attribute='state', reverse=true) |
      map(attribute='entity_id') |
      list
    }}

sequence:
  - condition: template
    value_template: "{{ all_scenes|count > 0}}"
  - service: scene.turn_on
    data_template:
      transition: !input transition
      entity_id: "{{ all_scenes[0] }}"
